### ISSUE TITLE
Load arguments from config file

### ISSUE THREAD

**Issue by reaganmcf** [reaganmcf/lightmon#2]
Load configuration/arguments from a `lightmon.toml` file that would be located in the root directory of a project. This is a feature in Nodemon that is essential for complicated configurations.

**Comment by reaganmcf** [comment]
I don't really know what syntax/format we want to use here. I just tried to create a basic config file off the top of my head and I got this:
```toml
[settings]
verbose = true
language = "shell"

[args]
script-path = "./script"
watch-patterns = ".c"
```

Although, I'm not really a fan because it doesn't feel intuitive. You have any ideas here @alayshahh?
